[package]
name = "doma_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
ascii = "0.5.0"
crossterm = "0.16.0"
minifb = "0.23.0"
sdl2 = "0.35.2"
fixed-vec-deque = "0.1.9"